### ISSUE TITLE
Improve chat plugin: cut message on word boundaries

### ISSUE THREAD

**Issue by morko** [saviola777/hhm-plugins#12]
For e.g. when displaying very long list of commands with the !help the commands get cut half. It would be nicer to cut the message between words.

**Comment by saviola777** [comment]
Think this is probably not relevant anymore :D Sorry I never got around to this.

**Comment by morko** [comment]
I made this plugin that exports a function to send long announcements https://github.com/morko/hhm-sala-plugins/blob/master/src/hr/utils.js#L52.
