### ISSUE TITLE
`sav/help` plugins `registerHelp` with roles not working

### ISSUE THREAD

**Issue by morko** [saviola777/hhm-plugins#9]
I have a plugin that defines the helps like so:

```js
let help = room.getPlugin(`sav/help`);
if (help) {
  const rolesToViewHelp = [
    'admin',
    'host'
  ];
  help.registerHelp(`kick`, ` PLAYER_NAME`, { roles: rolesToViewHelp });
  help.registerHelp(`ban`, ` PLAYER_NAME`, { roles: rolesToViewHelp });
  help.registerHelp(`unban`, ` PLAYER_ID`, { roles: rolesToViewHelp });
  help.registerHelp(`banlist`, ``, { roles: rolesToViewHelp });
}
```

In room as unauthorized player it still shows the commands when using `!help`.

I tried using the `sav/plugin-control` plugin in the same environment. With that plugin the `roles` options seemed to work.

The plugin that I tried to use it with gets loaded with `HHM.manager.addPluginByCode` function after the `postInit`.

**Comment by saviola777** [comment]
Could you include the code for the handler definitions? If you specify a number of arguments for the handler, you also need to pass that to `registerHelp`.

**Comment by morko** [comment]
Sorry I did not realize that. Seems to work with `numArgs` included.
